spring.application.name=CarrerPortal
# ===================================================================
# Application & Server Configuration
# ===================================================================
server.port=8080

# ===================================================================
# PostgreSQL Database Connection
# ===================================================================
# Replace 'jobconnect_db' with your actual database name if different
spring.datasource.url=jdbc:postgresql://database-2.cyje4eq0c2fg.us-east-1.rds.amazonaws.com:5432/CareerNest
spring.datasource.username=postgres
spring.datasource.password=GetAJob2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# Spring Data JPA / Hibernate Configuration
# ===================================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically updates the database schema according to model entities (Job, Application)
# Options: update | create | create-drop | validate | none
spring.jpa.hibernate.ddl-auto=update

# Print formatted SQL queries in the console log for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

twilio.account.sid=${TWILIO_ACCOUNT_SID:dummy_sid}
twilio.auth.token=${TWILIO_AUTH_TOKEN:dummy_token}
twilio.phone.number=${TWILIO_PHONE_NUMBER:dummy_phone}